### ISSUE TITLE
Malformed data generated in special case

### ISSUE THREAD

**Issue by underhood** [dmendel/bindata#100]
Environment Ruby 2.4.2-2-x64 on Win7

BinData class generates malformed file if string length exactly 10 (for 9 and 11 it seems working well). Please see https://github.com/underhood/RubyBinDataBug simple code and tests that demonstrate bug along with output generated in my system.

```ruby
class SimpleRecord < BinData::Record
endian  :little
    uint8   :direction
    uint32  :datalen, :value => lambda { data.length }
    string  :data, :read_length => :datalen
end
```
if write file with following code: (data length is 10, if string is longer or shorter it works ok)
```ruby
excerpt = SimpleRecord.new
excerpt.direction = 1
excerpt.data = "\x30\x31\x32\x33\x34\x35\x36\x37\x38\x39"
fout = File.open('output\test_3_len_10_bug.Bin', 'w')
excerpt.write(fout)
fout.close
```
when reading it with this code:
```ruby
fin = File.open('output\test_3_len_10_bug.Bin', 'r')
excerpt_load = SimpleRecord.read(fin)
fin.close
```
I get following error:
```
Error: test_3_len_10_bug(TestSimpleRecord): IOError: data truncated
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bindata-2.4.3/lib/bindata/io.rb:315:in `r
ead'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bindata-2.4.3/lib/bindata/io.rb:276:in `r
eadbytes'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bindata-2.4.3/lib/bindata/string.rb:118:i
n `read_and_return_value'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bindata-2.4.3/lib/bindata/base_primitive.
rb:129:in `do_read'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bindata-2.4.3/lib/bindata/struct.rb:139:i
n `block in do_read'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bindata-2.4.3/lib/bindata/struct.rb:139:i
n `each'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bindata-2.4.3/lib/bindata/struct.rb:139:i
n `do_read'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bindata-2.4.3/lib/bindata/base.rb:147:in
`block in read'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bindata-2.4.3/lib/bindata/base.rb:254:in
`start_read'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bindata-2.4.3/lib/bindata/base.rb:145:in
`read'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bindata-2.4.3/lib/bindata/base.rb:21:in `
read'
C:/MiscTools/RinasTooling/RubyBinDataBug/test_SimpleRecord.rb:53:in `test_3_len_
10_bug'

     52:         fin = File.open('output\test_3_len_10_bug.Bin', 'r')
  => 53:         excerpt_load = SimpleRecord.read(fin)
     54:         fin.close
```
When looking at generated file this is content (which seems malformed to me):
```
01 0D 0A 00 00 00 30 31 32 33 34 35 36 37 38 39
```
As you can see length of string seems to be written as 00 00 0A 0D (little endian) which is 2573 decimal and which is obviously nonsense.
Do I do something wrong? Why does it work correclty for other string lengths?
For example same code but string only long 9 chars. Writed file is generated correctly and read back by bin data without error. Sample of file with 9 byte string:
```
01 09 00 00 00 30 31 32 33 34 35 36 37 38
```
the second field (length of string 4Byte UINT) is 00 00 00 09 here as expected and everything works well

**Comment by dmendel** [comment]
> Environment Ruby 2.4.2-2-x64 on Win7

> fin = File.open('output\test_3_len_10_bug.Bin', 'r')
> fout = File.open('output\test_3_len_10_bug.Bin', 'w')

Windows handles binary files is unexpected ways.

Use `'rb'` instead of `'r'`, and `'wb'` instead of `'w'`.

Let me know if you still have problems.

**Comment by underhood** [comment]
Thanks a lot. Seems to have been the issue. Maybe some warning in Docu/Wiki for other poor souls who have to use Ruby on Windows :P

**Comment by dmendel** [comment]
Good idea. I added it to the FAQ.
