### ISSUE TITLE
Question about bytes escaping

### ISSUE THREAD

**Issue by Alexey1100** [dmendel/bindata#101]
Let's say I'm having the following class declared, where `0x1e` bytes in `payload ` should be replaced with two-byte sequence `0x1d0x01` and `0x1d` bytes should be replaced with `0x1d0x02`. 

What would be the most optimal solution?

```ruby
class Packet < BinData::Record
  endian :little
  uint8  :head, asserted_value: 0x1e
  struct :payload do
   # TODO: Escaping 0x1e
   uint8  :id
   string :data, length: 60
  end
  uint8  :tail, asserted_value: 0x1e
end
```

**Comment by Alexey1100** [comment]
Currently I'm thinking about defining a class with custom `do_read` and `do_write` methods, but not sure if it's the right way.

```ruby
module BinData
  class RecordEsc < Record
    def do_read(io)
      # Undo escaping in IO stream
      super(io)
    end

    def do_write(io)
      # Do escaping in IO stream
      super(io)
    end
  end
end

class PayloadEscaped < BinData::RecordEsc
  string :payload, length: 60
end

class Packet < BinData::Record
  endian :little
  uint8  :head, asserted_value: 0x1e
  payload_escaped :data
  uint8  :tail, asserted_value: 0x1e
end
```

**Comment by Alexey1100** [comment]
Thank you.
The solution looks good for a single type, but in my case `:payload` has quite a complicated structure, with lots of nested records of different types.

**Comment by dmendel** [comment]
There is no good single solution for this case where a stream has multiple encodings.

Your best approach would be to split the parsing into three steps.
1. Use BinData to decode the data preceding `payload`.
2. Read the payload as a ruby string, unescape it, then use BinData to parse it.
3. Use BinData to decode the data following `payload`.

I'll leave this open as a wishlist for now while I decide whether this feature is within the scope of BinData or not.

**Comment by dmendel** [comment]
Wishlist: Support different encoding within a steam.

Syntax would look something like:
```ruby
class A < BinData::Record
  int8 :a
  int8 :b
  section :c, encoding: :gzip do
    int8 :strlen
    string :str, initial_length: :strlen
  end
end
```
