### ISSUE TITLE
Does a conditional block exist that does not define a struct?

### ISSUE THREAD

**Issue by Tails** [dmendel/bindata#103]
I have a file with tens of properties. They have been added over different versions of the file's development. I would like to specify them in conditional tranches, but without using a struct and without having to specify :only_if on each one.

Currently I'm doing this:

```
class Conditionals < BinData::Record
    struct :v2props, only_if: :version_2? do
        uint32le :prop1
        uint32le :prop2
     end

     struct :v3props, only_if: :version_3? do
        uint32le :prop3
        uint32le :prop4
     end
end
```

but I would like the properties to still be defined on the main object instead of in structs so I can do:

```
class Conditionals < BinData::Record
    only_if :version_2? do
        uint32le :prop1
        uint32le :prop2
     end

     only_if :version_3? do
        uint32le :prop3
        uint32le :prop4
     end
end

conditionals.prop1
conditionals.prop3
```

Is this possible? Does an anonymous :only_if block exist?

I've tried doing this with an anonymous struct, but the properties are then not externally accessible.

**Comment by dmendel** [comment]
Use `Choice`,  not `only_if`.

Define self-contained Records for each version then use `Choice` to select the correct record to use.

If you want a field to be accessible at the top level, define an appropriate method.
e.g.
```ruby
def x; some.nested.x end
```
