### ISSUE TITLE
Rename :onlyif to :if

### ISSUE THREAD

**Issue by Tails** [dmendel/bindata#105]
There is probably a reason :onlyif was chosen instead of just :if. Is this because of some conflict that would otherwise exist?

If that's not the case, it would be nice if instead of :onlyif, or in addition to, it would be possible to use :if and :unless. This way, it's more consistent with ActiveRecord: http://guides.rubyonrails.org/active_record_validations.html#using-a-symbol-with-if-and-unless

When I got started using the library it took me a while to realize half my code was trying to use :if instead of :onlyif, though the documentation is clear! :)

**Comment by dmendel** [comment]
BinData has been around for 11 years and is currently in maintenance. Yes, there are minor naming issues (`String`'s `:length` is another).

Changing these names would provide a minor increase in readability.

However, this is not worth the cost of forcing people to change existing codebases for a minor cosmetic improvement.

Supporting both `:onlyif` and `:if` is a poor solution as codebases mixing the two will have worse readability than before.

The more pragmatic solution is to leave the names as they are.

**Comment by Tails** [comment]
Thank you for the rationale!
