### ISSUE TITLE
uint32be not working?

### ISSUE THREAD

**Issue by lclemence** [dmendel/bindata#109]
I manage to make it work to convert these latitude and longitude :
```
0F0DCDE4 – Longitude 252562916 = 25, 2562916o N
20959D30 – Latitude 546676016 = 54,6676016 o E
```
as 
```
class LittleExample < BinData::Record
    string :latitude, :length => 8
end
a = LittleExample.new
b = a.read(a)
puts b[:latitude].to_i(16)
```
but it seems not to be what i should do, instead i should be able to use uint32be (Big Endian) but this is not working. Could you explain to me why?

**Comment by dmendel** [comment]
Please provide the exact 8 byte string you are using in your LittleExample, and the expected result.

**Comment by dmendel** [comment]
Is the string you are reading in "0F0DCDE4", or is it "\x0f\x0d\xcd\xe4"?

If it's the former then it's not binary data, it's text data (i.e. ASCII or UTF-8).

BinData is a tool for working with binary data.

If your data is text data, then there are more appropriate tools to use (parsers and lexers).

**Comment by lclemence** [comment]
Good I get it! 
```
require 'hex_string'
require 'bindata'
class LittleExample < BinData::Record
  int32be :b
end
a = LittleExample.new
a.read('0F0DCDE4'.to_byte_string) => 252562916
```
give me the write answers. Thank you!
