### ISSUE TITLE
Support little endian bitfields

### ISSUE THREAD

**Issue by byteit101** [dmendel/bindata#110]
I was trying to use bindata to parse the FAT filesystem structure, and came across this issue. FAT stores dates in a bitfield in a 16-bit little-endian integer. It doesn't appear to me that bindata supports parsing such things nicely (first example), and I had to manually deal with endianness myself (second, working example):

```rb
require 'bindata'
require 'date'

EXAMPLE_DATE = "XN" # 2019-02-24 in FAT32 format (little endian bitfield)
puts "Actual FAT Date: 2019-02-24"

class ExpectedFatDateFmt < BinData::Record
	endian :little # appears to be ignored
	# uint16[0] = [year7, month4, day5]
	
	bit7 :year_off # epoch 1980
	bit4 :month
	bit5 :day
	
	virtual :year, :value => -> { 1980 + year_off }
	
	def snapshot
		Date.new(year,month,day).to_s
	end
end

print "ExpectedFatDateFmt: "
puts ExpectedFatDateFmt.read(EXAMPLE_DATE)


class WorkingFatDateFmt < BinData::Record
	endian :big
	# manually do the little-endianness ourselves
	# uint8[1] = [year7, month_hi1], uint8[0] = [month_lo3, day5]
	
	bit3 :month_lo
	bit5 :day
	bit7 :year_off  # epoch 1980
	bit1 :month_hi
	
	virtual :month, :value => -> { (month_hi << 3) | month_lo }
	virtual :year, :value => -> { 1980 + year_off}
	
	def snapshot
		Date.new(year,month,day).to_s
	end
end

print "WorkingFatDateFmt: "
puts WorkingFatDateFmt.read(EXAMPLE_DATE)

```

Output:
```txt
Actual FAT Date: 2019-02-24
ExpectedFatDateFmt: 2024-02-14
WorkingFatDateFmt: 2019-02-24
```
Expected Output:
```txt
Actual FAT Date: 2019-02-24
ExpectedFatDateFmt: 2019-02-24
WorkingFatDateFmt: 2019-02-24
```

Ruby: MRI 2.5.1 & JRuby 9.2.0.0
Bindata: 2.4.4

**Comment by dmendel** [comment]
Thanks for the detailed report.

Use little endian bitfields as documented here:
    https://github.com/dmendel/bindata/wiki/PrimitiveTypes#bit-based-integers

i.e.
    bit5le :day
    bit4le :month
    bit7le :year_off

**Comment by byteit101** [comment]
Brilliant! That works for me! I was on that page but somehow missed it. Might it be a good idea to make "bitfields" a linked header name? Or perhaps add a reference-style section separate from the guide-style documentation? I know I've used this library a few times a year for the past 4 or 5 years, and always constantly find myself flipping through all the wiki pages trying to find what I'm looking for...
