### ISSUE TITLE
Feature Idea: Katai Struct import?

### ISSUE THREAD

**Issue by rgzn** [dmendel/bindata#111]
I wonder whether it would be possible to make an import feature that could take kaitai struct .ksy specification files and translate them into bindata objects. It's nice how kaitai is independent of language, but it lacks the ability to write out binary files like bindata.

**Comment by dmendel** [comment]
It certainly looks possible as kaitai's features are a mostly a subset of BinData's (with the exception of their Processing spec).

It's not something that I'm interested in doing, but I'll happily link to your implementation once you've done it.
