### ISSUE TITLE
Question about generate binary stream

### ISSUE THREAD

**Issue by tan-wei** [dmendel/bindata#114]
Thanks for this fabulous project. It makes me feel happy to parse many kinds of user desigin protol binary stream. But I have a question on the different direction: Is there any similar tool that we can generate a binary stream so elegant? I search it for some days, but I find it is not that elegant.
Thanks! Hope you have a good day.

**Comment by dmendel** [comment]
I don't understand your question.

BinData can both read and write binary data.

Is there some type of data you wish to write that BinData is unable to generate?

**Comment by tan-wei** [comment]
Sorry for my unfamiliar with write binary data with `bindata`.
Can `bindata` write binary stream whose types are all arbitrary width bits and no padding with each other? Thanks for your reply.

**Comment by dmendel** [comment]
Yes.

https://github.com/dmendel/bindata/wiki/PrimitiveTypes#bit-based-integers

Is this what you need?

**Comment by tan-wei** [comment]
I think so. Many projects, e.g. `kaitai-struct`, can not deal with this situation because of alignment. Thanks for your kind reply.
