### ISSUE TITLE
<top (required)>': superclass mismatch for class IPAddr (TypeError)

### ISSUE THREAD

**Issue by lilijreey** [dmendel/bindata#117]
https://github.com/dmendel/bindata/blob/c01145ac22d1d98fd9eb71d6a150b2648d942395/examples/tcp_ip.rb#L26

define IPAddr has error, change name to IpAddr is Ok
why?

**Comment by dmendel** [comment]
Yes, this was a typo. It should have been `IP_Addr` instead of `IPAddr`.

Thanks for the report.
