### ISSUE TITLE
Greedy parsing of fields

### ISSUE THREAD

**Issue by kzemek** [dmendel/bindata#118]
We're using bindata to parse sFlow records in [path-network/logstash-codec-sflow](https://github.com/path-network/logstash-codec-sflow). sFlow records often contain sample packet data, e.g ethernet header + IP header + TCP header, but sometimes only an ethernet header + IP header, or maybe only a half of the IP header.

The contents of messages are always well-defined in terms of their length, which makes `Buffer` an ideal choice especially in cases where we don't know how to decode the payload. But it seems that the only way to decode as much of the understood data as we can, a buffer definition would have to look like this:

```ruby
class IPV6Header < BinData::Buffer
  mandatory_parameter :size_header
  default_parameters :length => :size_header

  endian :big
  bit4 :ip_version, :onlyif => lambda { :size_header >= 1 }
  bit6 :ip_dscp, :onlyif => lambda { :size_header >= 2 }
  bit2 :ip_ecn, :onlyif => lambda { :size_header >= 2 }
  bit20 :ipv6_flow_label, :onlyif => lambda { :size_header >= 4 }
  uint16 :ip_payload_length, :onlyif => lambda { :size_header >= 6 }
  uint8 :ip_protocol, :onlyif => lambda { :size_header >= 7 }
  uint8 :ipv6_hop_limit, :onlyif => lambda { :size_header >= 8 }
  sflow_ip6_addr :src_ip, , :onlyif => lambda { :size_header >= 24 }
  sflow_ip6_addr :dst_ip, , :onlyif => lambda { :size_header >= 40 }

  # The inner records have to do the same thing
  choice :ip_data, :selection => :ip_protocol do
    tcp_header 6, :size_header => lambda { size_header - 320 }
    udp_header 17, :size_header => lambda { size_header - 320 }
    unknown_header :default, :size_header => lambda { size_header - 320 }
  end
end
```

Without the `onlyif`s, the parsing throws an error whenever we get to a field that would go over this `Buffer`'s length.

Is there a good way to parse such structures greedily, where it just steps out once it parsed every field that fit in the `Buffer`?

**Comment by dmendel** [comment]
There is no general way to parse an object that has been arbitrarily truncated.

You have two options:

1. Use `onlyif` as you've shown above, and hope you don't get truncation in the middle of a multibyte field.

2. Use a two-pass passing scheme. Read the truncated data as a byte string, extend this data with sufficient default bytes, then parse this data again.

There is no built-in support for either approach in BinData.
