### ISSUE TITLE
Support for varint

### ISSUE THREAD

**Issue by andywatts** [dmendel/bindata#124]
Has any work been done to support variable length integers aka varint?

If unfamiliar with varint, this post discuss...
https://carlmastrangelo.com/blog/lets-make-a-varint

**Comment by andywatts** [comment]
Here's a node module for reference...
https://github.com/chrisdickinson/varint#readme

**Comment by dmendel** [comment]
There are several different variable length integer encoding schemes.  See below for an example of implementing one.

https://github.com/dmendel/bindata/wiki/PrimitiveTypes#advanced-user-defined-primitive-types

You should be able to use this to help you implement your particular varint scheme.

**Comment by andywatts** [comment]
That's a great example.  :)
Drop the negative/positive part and it's same as protobuf's varint.
