### ISSUE TITLE
nbit and bit based integer

### ISSUE THREAD

**Issue by andywatts** [dmendel/bindata#126]
Really great library...Many Thanks!

I'm struggling to read bit based integers with dynamic number of bits.
I want to read between 4..16 bits and cast to int.

```
VarInt :numLongs                                # VarInt works great.
array :ids, :initial_length => 4096 do
    # bit16 :nbits => lambda { numLongs * 64 / 4096 }   # What I really want...throws EOF
    # bit4 :nbits => 4                                  # Works, but sometimes I need to read 5..8 bits
    bit16 :nbits => 4                                   # EOF error...trying to read 16bits?
end
array :light, type: :bit4le, initial_length: 4096
```

Perhaps I need a different approach?

**Comment by dmendel** [comment]
>I'm struggling to read bit based integers with dynamic number of bits.
>I want to read between 4..16 bits and cast to int.

Use `bit :nbits => X` instead of bit4 :nbits => X`.

:nbits only applies to bit, sbit, bit_le and sbit_le.

**Comment by andywatts** [comment]
Thanks.
Reading Minecraft chunks and the format looks more incompatible.
https://wiki.vg/Chunk_Format#Compacted_data_array

Think I need to read the longs and post process like [this](https://github.com/PrismarineJS/prismarine-chunk/blob/9b2510386bb8922cbc840f4d002c231a8c3e53c3/src/pc/common/BitArray.js#L43).
