### ISSUE TITLE
parse ole file err

### ISSUE THREAD

**Issue by CxcPDF** [dmendel/bindata#128]
Traceback (most recent call last):
        19: from /Users/java/cloudplat_contenthub4j/src/main/java/com/em/ruby/ole2xml.rb:9:in `<main>'
        18: from /Users/java/cloudplat_contenthub4j/src/main/java/com/em/ruby/ole2xml.rb:5:in `getTex'
        17: from /Users/java/cloudplat_contenthub4j/src/main/java/com/em/ruby/ole2xml.rb:5:in `new'
        16: from /Users/.rvm/gems/ruby-2.6.5/gems/mathtype-0.1.0/lib/mathtype.rb:24:in `initialize'
        15: from /Users/.rvm/gems/ruby-2.6.5/gems/bindata-2.4.8/lib/bindata/base.rb:21:in `read'
        14: from /Users/.rvm/gems/ruby-2.6.5/gems/bindata-2.4.8/lib/bindata/base.rb:145:in `read'
        13: from /Users/.rvm/gems/ruby-2.6.5/gems/bindata-2.4.8/lib/bindata/base.rb:253:in `start_read'
        12: from /Users/.rvm/gems/ruby-2.6.5/gems/bindata-2.4.8/lib/bindata/base.rb:147:in `block in read'
        11: from /Users/.rvm/gems/ruby-2.6.5/gems/bindata-2.4.8/lib/bindata/struct.rb:139:in `do_read'
        10: from /Users/.rvm/gems/ruby-2.6.5/gems/bindata-2.4.8/lib/bindata/struct.rb:139:in `each'
         9: from /Users/.rvm/gems/ruby-2.6.5/gems/bindata-2.4.8/lib/bindata/struct.rb:139:in `block in do_read'
         8: from /Users/.rvm/gems/ruby-2.6.5/gems/bindata-2.4.8/lib/bindata/array.rb:303:in `do_read'
         7: from /Users/.rvm/gems/ruby-2.6.5/gems/bindata-2.4.8/lib/bindata/array.rb:303:in `loop'
         6: from /Users/.rvm/gems/ruby-2.6.5/gems/bindata-2.4.8/lib/bindata/array.rb:305:in `block in do_read'
         5: from /Users/.rvm/gems/ruby-2.6.5/gems/bindata-2.4.8/lib/bindata/struct.rb:139:in `do_read'
         4: from /Users/.rvm/gems/ruby-2.6.5/gems/bindata-2.4.8/lib/bindata/struct.rb:139:in `each'
         3: from /Users/.rvm/gems/ruby-2.6.5/gems/bindata-2.4.8/lib/bindata/struct.rb:139:in `block in do_read'
         2: from (eval):2:in `do_read'
         1: from /Users/.rvm/gems/ruby-2.6.5/gems/bindata-2.4.8/lib/bindata/choice.rb:109:in `current_choice'
/Users/.rvm/gems/ruby-2.6.5/gems/bindata-2.4.8/lib/bindata/choice.rb:115:in `instantiate_choice': selection '102' does not exist in :choices for obj.equation[0].payload (IndexError)

and the file content is：
[2.docx](https://github.com/dmendel/bindata/files/5082118/2.docx)

**Comment by dmendel** [comment]
This looks like a problem with ole2xml, about which I know nothing.

**Comment by CxcPDF** [comment]
OK, thank you
