### ISSUE TITLE
Customize record Bindata name

### ISSUE THREAD

**Issue by bilby91** [dmendel/bindata#132]
Hello,

I'm trying to customize the name Bindata uses to register my class. I have  a project where we scope our bin data classes in modules and we can have collisions across modules. 

I'm looking for a way to do something like this:

```
class Namespace1::MyRecord < BinData::Record
  bindata_name :ns1_my_record
end

class Namespace2::MyRecord < BinData::Record
  bindata_name :ns2_my_record
end

class AggregateRecord < BinData::Record
  ns1_my_record
  ns2_my_record
end
```

**Comment by dmendel** [comment]
```ruby
class Namespace1::MyRecord < BinData::Record
  BinData::RegisteredClasses.register(:ns1_my_record, self)  
end
```

This will do it. I'll probably wrap the details behind a convenience method for the next release.

**Comment by bilby91** [comment]
@dmendel Thanks for the tip!

I've tried it but I'm still getting this warnings:

```
warning: replacing registered class Namespace2::MyRecord with Namespace1::MyRecord
```

Is there any gotcha I might be missing ?

Thanks before hand!
