### ISSUE TITLE
ActiveSupport 7 compatibility - Enumerable now contains a method called maximum

### ISSUE THREAD

**Issue by adfoster-r7** [dmendel/bindata#138]
Hi there; Firstly - thanks for the great gem! :+1:

Just thought I'd cross-reference this issue that one of our users ran into when they upgraded to ActiveSupport 7:

> ActiveSupport 7.0 adds Enumerable#maximum, but bindata gem considers all Hash instance methods as [reserved keywords](https://github.com/dmendel/bindata/blob/de567f8cbdc6db612b51fe27eddf4c358548ce08/lib/bindata/struct.rb#L64-L78). Since maximum is used as [property in a bit field](https://github.com/rapid7/ruby_smb/blob/1ccd35e65b4750102f74c606935d0f96ee602f8b/lib/ruby_smb/smb2/bit_field/directory_access_mask.rb#L33), the gem no longer wants to load

We implemented the fix on our side to rename `maximum` to a different name
https://github.com/rapid7/ruby_smb/pull/188

This is no longer an issue for our usage; but I just wanted to document this on the bindata gem as it might impact others too

**Comment by dmendel** [comment]
Thank you. I'll close this as it doesn't seem to warrant a change in BinData.
