### ISSUE TITLE
Rename parameter 'assert' as it shadows an existing method.

### ISSUE THREAD

**Issue by vinayak3qilabs** [dmendel/bindata#141]
NameError: Rename parameter 'assert' as it shadows an existing method.
     ensure_valid_names at C:/awe-jruby2/jruby-9.2.8.0/lib/ruby/gems/shared/gems/bindata-2.4.12/lib/bindata/params.rb:111
                   each at org/jruby/RubyArray.java:1800
     ensure_valid_names at C:/awe-jruby2/jruby-9.2.8.0/lib/ruby/gems/shared/gems/bindata-2.4.12/lib/bindata/params.rb:109
                to_syms at C:/awe-jruby2/jruby-9.2.8.0/lib/ruby/gems/shared/gems/bindata-2.4.12/lib/bindata/params.rb:103
               optional at C:/awe-jruby2/jruby-9.2.8.0/lib/ruby/gems/shared/gems/bindata-2.4.12/lib/bindata/params.rb:66
    optional_parameters at C:/awe-jruby2/jruby-9.2.8.0/lib/ruby/gems/shared/gems/bindata-2.4.12/lib/bindata/params.rb:12
  <class:BasePrimitive> at C:/awe-jruby2/jruby-9.2.8.0/lib/ruby/gems/shared/gems/bindata-2.4.12/lib/bindata/base_primitive.rb:52
       <module:BinData> at C:/awe-jruby2/jruby-9.2.8.0/lib/ruby/gems/shared/gems/bindata-2.4.12/lib/bindata/base_primitive.rb:49
                 <main> at C:/awe-jruby2/jruby-9.2.8.0/lib/ruby/gems/shared/gems/bindata-2.4.12/lib/bindata/base_primitive.rb:3

Is anyone help me to resolve above issue.

**Comment by dmendel** [comment]
Did you try renaming the parameter 'assert' to something else?

**Comment by vinayak3qilabs** [comment]
yes @dmendel. i have renamed assert in this gem then it is working, but this bindata is dependent gem in project, so every time need to rename assert in respective file.

**Comment by dmendel** [comment]
Just so I understand correctly, your project (or one of the gems it uses) has added `#assert` to `Kernel`. Is this correct?

**Comment by vinayak3qilabs** [comment]
correct  @dmendel

**Comment by vinayak3qilabs** [comment]
@dmendel  this issue still not resolved. getting same error.

**Comment by dmendel** [comment]
Is the `#assert` method something you have implemented yourself, or is it from a gem you are using? If a gem, which one?

**Comment by vinayak3qilabs** [comment]
In following gems 'assert' method is present
Mustermann-2.0.2

scrivener-0.0.3
will_paginate-3.2.1

xmlrpc-0.3.0

sane-0.25.8

minitest-5.10.3

rack-2.2.4

test-unit-3.2.8

**Comment by vinayak3qilabs** [comment]
@dmendel  OR if  we  add 'assert' keyword  in below method in params.rb file, what impact will this have in gem working?

       `def self.invalid_parameter_names
        @invalid_names ||= begin
          all_names = LazyEvaluator.instance_methods(true)
          allowed_names = [:name, :type, **:assert**]
          invalid_names = (all_names - allowed_names).uniq
          Hash[*invalid_names.collect { |key| [key.to_sym, true] }.flatten]
        end`

**Comment by dmendel** [comment]
Does adding `:assert` to the list of allowed_names solve your problem? I'm having trouble reproducing the issue.

**Comment by dmendel** [comment]
Perhaps try rearranging the order that your require the gems. If you require bindata before the other gems, then it shouldn't complain.

**Comment by vinayak3qilabs** [comment]
Hey @dmendel  thanks for the pointer. This resolved our issue.
