### ISSUE TITLE
Dynamic integer

### ISSUE THREAD

**Issue by marek22k** [dmendel/bindata#150]
Hello,

I want to parse an integer value with a length that I can specify dynamically (from a variable). Does this feature already exist? Could it be implemented?
```ruby
uint :dynamic_value, length: :dynamic_value_length
```

(a little bit like https://github.com/dmendel/bindata/issues/126)

**Comment by dmendel** [comment]
>I want to parse an integer value with a length that I can specify 
>dynamically (from a variable). Does this feature already exist?

For big and little endian integers, use bit-based integers.

https://github.com/dmendel/bindata/wiki/PrimitiveTypes#bit-based-integers

For other formats, see

https://github.com/dmendel/bindata/wiki/PrimitiveTypes#advanced-user-defined-primitive-types
