### ISSUE TITLE
Question: High memory usage

### ISSUE THREAD

**Issue by marek22k** [dmendel/bindata#151]
Hello,

I have written a script with BinData to read MRT files, however the script consumes an enormous amount of memory. If I limit the readout to 100 entries, it consumes 10GB of memory alone. Is there anything I can do about this?

Code: https://codeberg.org/mark22k/MrtParser/src/commit/6675400ebe9a3df1401314dd6d7d3ba6fb336cd5
Example MRT file: [master4_latest.mrt.bz2](https://paste.i2pd.xyz/?1be19b7ab281e4eb#3ffdpciEK2Qxzwy1xz3FFEpjQv2B91bAtBTeHbY3Bxox)
Limiting: Do `read_until: -> { index >= 100 - 1 }` in [parser.rbL333](https://codeberg.org/mark22k/MrtParser/src/commit/6675400ebe9a3df1401314dd6d7d3ba6fb336cd5/parser.rb#L333)

**Comment by dmendel** [comment]
>I have written a script with BinData to read MRT files, however the 
>script consumes an enormous amount of memory.

You are reading and storing each MRT entry into memory, and then 
processing them one at a time.

Instead of using `array :read_until`, read and process each entry one at 
a time.

i.e.

```ruby
class MrtEntry < BinData::Record
   CommonHeader :header
   buffer :data, length: -> { header.length1 } do
       choice selection: -> { [header.type1, header.subtype] } do
           PeerIndexTable [13, 1] # TableDumpV2 (13) -> PeerIndexTable (1)
           RibUnicast [13, 2] # TableDumpV2 (13) -> RibIPv4Unicast (2)
           RibUnicast [13, 4] # TableDumpV2 (13) -> RibIPv6Unicast (4)
           RibUnicast [13, 8] # TableDumpV2 (13) -> RibIPv4UnicastAddpath (8)
           RibUnicast [13, 10] # TableDumpV2 (13) -> RivIPv6UnicastAddpath(10)
       end
   end
end
```

**Comment by marek22k** [comment]
Thanks for the answer.
