### ISSUE TITLE
EOFError when reading unaligned little endian bit integers

### ISSUE THREAD

**Issue by catlee** [dmendel/bindata#153]
Apologies if this is expected behaviour, I'm just learning bindata.

I have some unaligned signed little endian integers I'm trying to parse, and getting EOFError when running code like this:

```ruby
require "bindata"

class Test < BinData::Record
  bit2 :tag
  bit6le :a
end

data = "\xa4"
puts Test.read(data)
```

If you change `:a` to `bit6`, then it doesn't raise an error, but doesn't parse the data as little endian.

**Comment by dmendel** [comment]
I think you are misunderstanding what big vs little endian bitfields 
are.  It doesn't make sense to mix them.

You most likely want to use big endian bitfields unless you are dealing 
with very old data formats.

Here is an illustration of what big vs little endian bitfields are.
https://github.com/dmendel/bindata/blob/master/lib/bindata/io.rb#L19-L29

What are you trying to achieve?  If you post the binary data and how you 
want to extract it I can convert that to BinData for you.

**Comment by catlee** [comment]
I was hoping that since a record defines its fields from least to most significant bytes, and that you can mix the endianness between different byte fields, that I would be able to do the same within a bitfield. In the example above I would expect that `:tag` would use the 2 most significant bits of the byte, and `:a` would use the 6 least significant bits.

```
76543210
ttaaaaaa
```

The docs kind of imply this is possible: https://github.com/dmendel/bindata/wiki/Records#specifying-default-endian. Perhaps a note could be added there (or in the section about bitfields) that you can't mix endian-ness?

Should the `endian` directive apply for records containing bitfields?

**Comment by dmendel** [comment]
```ruby
class Test < BinData::Record
   bit2 :tag
   bit6 :a
end

p Test.read("\xa4") #=> {:tag=>2, :a=>36}
```

Here is your example in BinData.  Is this what you expect?

```
0xa4 is 1010 0100 in binary

0b10     is 2 in decimal
0b100100 is 36 in decimal
```

**Comment by dmendel** [comment]
Yes, your understanding is correct for within a single byte.

I recommend you don't use little endian bitfields unless you know you have to.  It gets tricky when you span across a byte boundary.
