### ISSUE TITLE
How can I read 2 bytes (little endian) and then interpret that value as a bit field?

### ISSUE THREAD

**Issue by GrumpyGourmand** [dmendel/bindata#154]
Hi,

I'm working on a personal project in Ruby using Bindata (thank you for developing this) and I'm wondering if something I'm trying to do is possible, as I have not been able to get it working how I need.

So, I'm trying to read a 2-byte value from a file (stored little endian) which represents a bit-field where the first 7 bits is one number, and the last 9 bits comprise another.  So, as viewed in a hex editor, I'm trying to read the 2-byte sequence (0x38, 0x02), which when taking endianness into account, represents the value 0x238 which is 0000001000111000 in binary.  I need the 0000001 as one number, and the 000111000 as another (so, 1 and 0x38).

My code looks like this:

```
class FF7Item < BinData::Record
  bit7  :quantity
  bit9  :item_index
end
```
I think I'm getting myself confused as to how endianness applies to bit fields.  I've tried specifying bit7le and bit9le, or just using "endian  :little" at the top before bit7, but nothing I've tried is giving me the desired result.  I'd love any insight you could provide regarding what I need to do differently to get the result I've specified.  Thank you.

**Edit**:  I've managed to get the result I was looking for by changing my code to this:
```
class FF7Item < BinData::Record
  endian  :little

  uint16  :item
  virtual :quantity, value: -> { item >> 9 }
  virtual :item_index, value: -> { item & 0x1FF }
end
```

Please let me know if there's a way of doing this without the manual bit manipulation.

**Comment by dmendel** [comment]
Reverse the ordering of the bitfields when using little endian.

```
class FF7Item < BinData::Record
   bit7le  :quantity
   bit9le  :item_index
end
```

**Comment by GrumpyGourmand** [comment]
That did the trick.  Thank you.
