### ISSUE TITLE
Array read_until: -> { :eof } feature is broken

### ISSUE THREAD

**Issue by 8bit-mate** [dmendel/bindata#156]
Hello,

Array's `read_until: -> { :eof }` feature is broken: it doesn't read data to the end of a file/string. It reads only the first element and then stops.

**Ways to reproduce**
Consider the following binary format representation:
```Ruby
STR_LENGTH = 16 # bytes

class Header < BinData::Record
  uint32le :signature, asserted_value: 0xFF00BA55
end

class TextEntry < BinData::Record
  stringz :payload
  string :padding, length: -> { STR_LENGTH - padding.rel_offset }, pad_byte: 0x20
end

class MyFormat < BinData::Record
  header :header

  array :str_arr, read_until: -> { :eof } do
    text_entry
  end

  count_bytes_remaining :byte_cntr
end
```

Please note that I also added the `count_bytes_remaining` at the very end for the debugging purposes.

And then create a `MyFormat` obj out a test data:

```Ruby
test_data = "U\xBA\x00\xFFfoo\x00            bar\x00            "
MyFormat.read(test_data).inspect
```

**Expected output:**
```Ruby
"{:header=>{:signature=>4278237781}, :str_arr=>[{:payload=>\"foo\", :padding=>\"            \"}, {:payload=>\"bar\", :padding=>\"            \"}], :byte_cntr=>0}"
```

**Real output:**
```Ruby
"{:header=>{:signature=>4278237781}, :str_arr=>[{:payload=>\"foo\", :padding=>\"            \"}], :byte_cntr=>16}"
```

Please note that the real output shows that `byte_cntr => 16`, so the parser "knows" that 16 bytes are still remaining before the EOF, but it doesn't read this data.

**My environment**
- ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
- bindata (2.4.15)

**Comment by dmendel** [comment]
Use `read_until: :eof`

not `read_until: -> { :eof }`
