### ISSUE TITLE
Seeking to records at arbitrary offsets within a file

### ISSUE THREAD

**Issue by aidansteele** [dmendel/bindata#23]
A common sight in binary formats is a "table of contents" at the start of a file, which may contain an array of offsets to records later in the file. The records may be sparsely populated in the file.

What is the best pattern to deal with this? I understand that `bindata` has support for seeking forwards, but not necessarily "rewinding" back to the original point. Is this beyond the scope of this project and should be handled at a higher level?

**Comment by jure** [comment]
Just for an additional example, I have a similar issue which requires `adjust_offset`, i.e. a record is either stored as two bytes or as six bytes, depending on the first byte.

> A nudged record has the mtefOPT_NUDGE option (0x8) and the option byte is followed immediately by the nudge offset. The nudge offset consists of either two bytes or six, depending on the amount of offset. If -128 <= dx < +128 and -128 <= dy < +128, then the offsets are stored as two bytes, dx followed by dy, where each value has 128 added to it before it is written. Otherwise, two bytes of 128 are stored, followed by the offsets, dx and dy, stored as 16-bit values, low byte followed by high byte.

**Comment by dmendel** [comment]
@jure your example doesn't need `:adjust_offset`. 

```ruby
class MyRecord < BinData::Record
  ...
  uint8 :option
  struct :nudge, :only_if => :nudged_offset? do
    uint8 :_small_dx
    uint8 :_small_dy
    uint16 :_large_dx, :only_if => lambda { _small_dx == 128 }
    uint16 :_large_dy, :only_if => lambda { _small_dy == 128 }
  end

  def nudged_offset?
    (option & OPT_NUDGE).non_zero?
  end

  def dx
    if nudged_offset?
      (nudge._small_dx == 128) ? nudge._large_dx : (nudge._small_dx - 128)
    else
      0
    end
  end

  def dx=(val)
    if nudged_offset?
      if val >= -128 && val < 128
        nudge._small_dx = val + 128
      else
        nudge._small_dx = 128
        nudge._large_dx = val
      end
    end
  end
  ...
end
```

**Comment by jure** [comment]
Thanks for the example, @dmendel! That certainly works.

This is what I did before (with the actual values, i.e. +128, as I'm only reading, adjusted outside of the Record):

```
  class SmallOffset < BinData::Record
    int8 :dx
    int8 :dy
  end

  class BigOffset < BinData::Record
    endian :little
    skip length: 2
    int16 :dx
    int16 :dy
  end

  class Nudge < BinData::Record
    endian :little
    int8 :first_byte

    choice :nudge, selection: :first_byte, adjust_offset: -1 do
      big_offset 128
      small_offset :default
    end
  end
```

**Comment by jure** [comment]
@dmendel Off-topic, but out of curiosity, what would be a best practice way to have `dx` and `dy` be exposed in the snapshot, while keeping `_small_dx`, `_small_dy`, `_large_dx` and `_large_dy` hidden, and keeping the existing nested snapshotting functionality.

**Comment by dmendel** [comment]
If you use [hide](../wiki/AdvancedTopics#debugging) and [virtual fields](../wiki/Records#virtual-fields) then there is no need to override snapshot.

See the following. It automatically handles the 128 adjustment and works for reading and writing.
```ruby
class MyRecord < BinData::Record
  hide :nudge
  ...
  uint8 :option
  struct :nudge, :onlyif => :nudged_offset? do
    uint8    :_small_dx, :value => lambda { (dx >= -128 && dx < 128) ? dx + 128 : 128 }
    uint8    :_small_dy, :value => lambda { (dy >= -128 && dy < 128) ? dy + 128 : 128 }
    uint16le :_large_dx, :value => :dx, :onlyif => lambda { _small_dx == 128 }
    uint16le :_large_dy, :value => :dy, :onlyif => lambda { _small_dy == 128 }
  end

  virtual :dx, :initial_value => lambda { (nudge._small_dx == 128) ? nudge._large_dx : nudge._small_dx - 128 }
  virtual :dy, :initial_value => lambda { (nudge._small_dy == 128) ? nudge._large_dy : nudge._small_dy - 128 }

  def nudged_offset?
    (option & OPT_NUDGE).non_zero?
  end
end
```
The above is unfortunately messy because the small and large dx and dy are interwoven. If they were grouped together (small_dx, large_dx, small_dy then large_dy) then we could do it in a more tidy fashion.
```ruby
class DeltaInt < BinData::Primitive
  uint8    :small
  uint16le :large, :onlyif => lambda { small == 128 }

  def get
    (small == 128) ? large : small - 128
  end

  def set(val)
    if val >= -128 && val < 128
      self.small = val + 128
    else
      self.small = 128
      self.large = val
    end
  end
end

class MyRecord < BinData::Record
  delta_int :dx, :onlyif => :nudged_offset?
  delta_int :dy, :onlyif => :nudged_offset?
end

```
