### ISSUE TITLE
Offset-based reading

### ISSUE THREAD

**Issue by madprogrammer** [dmendel/bindata#52]
Suppose I have a table of offsets to some child objects, given that the offsets in the table are relative to the parent:

```
    class BlobIndex < BinData::Record
        uint32be :type
        uint32be :offs
    end

    class Blob < BinData::Record; end;

    class SuperBlob < BinData::Record
        uint32be :len
        array :blob_offsets, :type => :blob_index, :initial_length => :len
        # Blob objects follow, according to the offsets, the offset of the first blob will be equal to the length of the blob_offsets array in bytes
    end
```

I couldn't find how can I make such structure into an array of `Blob` records. I have also tried:
```
array :blob_offsets, :type => :blob_index, :initial_length => :len
array :blobs, :initial_length => :len do
   blob :adjust_offset => lambda { offset[index].offs }
end
```

Which didn't work properly, probably because the offset is adjusted related to the start of the IO, not the start of `SuperBlob` object. Is it possible to rebase the offset calculation to a given field in the `SuperBlob` object. I'm trying to port the following code from Python (notice it has a feature called `Anchor`: https://github.com/comex/cs/blob/master/macho_cs.py)

**Comment by dmendel** [comment]
BinData operates in a single pass as single pass formats are easier to comprehend. Easy comprehension is a primary design goal.

The offset example above is not necessarily single pass, as the offsets may point to earlier in the stream. Solving this example requires multi pass processing, introduced in BinData 2.3.0.

Here is how to do this with BinData:
```ruby
class Blob < BinData::Record; end;

class SuperBlob < BinData::Record
  endian :big

  uint32 :len
  array  :blob_offsets, :initial_length => :len do
    uint32 :type
    uint32 :offs
  end

  array :blobs, :initial_length => :len do
    delayed_io :type => :blob,
               :read_abs_offset => lambda { offset_adjustment + blob_offsets[index].offs }
  end
end
```
Calling `SuperBlob#read` will read the blob offsets, but not the blobs.
```ruby
sb = SuperBlob.read(io)
```
You need to explicitly call `#read_now!` on the delayed objects to perform the additional passes. This lets you control the timing of the multiple passes which may be necessary depending on your circumstances.
```ruby
sb.blobs.each { |blob| blob.read_now! }
```
