### ISSUE TITLE
Support for enum types?

### ISSUE THREAD

**Issue by nileshtrivedi** [dmendel/bindata#56]
It would be nice to read an int and look it up in an array of symbols like this:

    enum :status, :values => [:pending, :successful, :failed]

such that the read and write methods work transparently and also check the validity of the enum field.

**Comment by dmendel** [comment]
An enum type is too specialised to add to core. What is the underlying integer representation? Are the values contiguous? Do they start from 0 or 1? What is the desired behaviour of values outside the specified range?

Enum types are specific to the application. You can easily create one by subclassing `BinData::Primitive`.

https://github.com/dmendel/bindata/wiki/PrimitiveTypes#user-defined-primitive-types

Additionally, symbol values already have an existing meaning in BinData.
```ruby
class A < BinData::Record
  int8 :val1
  int8 :val2, :value => :val1  # shortcut for :value => lambda { val1 }
end
```

If you create a type with symbol values then be aware that you can't use it as the selector for `Choice`.

https://github.com/dmendel/bindata/wiki/CompoundTypes#key
