### ISSUE TITLE
Question: Better way to customize snapshot types ?

### ISSUE THREAD

**Issue by jeromeag** [dmendel/bindata#57]
Hi,
Firts of all, thank you for this gem, it seems that you have thought to everything.

To customize my test output, i did this way

```
require 'bindata'

class TodSnapshot
  def initialize(value)
    @value = value
  end

  def inspect
    "#{@value}(#{"0x%08x" % @value})"
  end
end

class Tod < BinData::Primitive
  endian :big
  uint32 :val

  def get ; self.val; end
  def set(v) ; self.val = v ; end

  def snapshot
    TodSnapshot.new(self.val)
  end
end

class Pouet < BinData::Record
  endian :big
  tod    :sent_tod
end

pouet = Pouet.new.read("\x01\xab\x23\xcd")

require 'pp'
pp pouet.snapshot
```

My output is the expected one:
```
{:sent_tod=>27993037(0x01ab23cd)}
```

And my question is the following : is there any more "direct" way to do this ?

Thanks in advance,

Jérôme

**Comment by dmendel** [comment]
Yes, your above solution is the easiest way to do it.

You will probably want to implement `#method_missing` and `#respond_to?` in your snapshot class, otherwise the `#assign` method will break.

```
class TodSnapshot
  def initialize(value)
    @value = value
  end

  def inspect
    "#{@value}(#{"0x%08x" % @value})"
  end

  def respond_to?(sym)
    @value.respond_to?(sym)
  end

  def method_missing(sym, *args, &block)
    @value.method_missing(sym, *args, &block)
  end
end
```

For a more detailed customisation, the visitor design pattern would probably be easier.

**Comment by jeromeag** [comment]
Thank you.
