### ISSUE TITLE
Expose next byte to ReadUntilPlugin

### ISSUE THREAD

**Issue by jamesottaway** [dmendel/bindata#58]
I'm trying to read this response of a call to my Yubikey:

``` ruby
"\x72\x03foo\x72\x03bar\x90\x00"
```

into the following BinData record:

``` ruby
class Entry < BinData::Record
  uint8 :name_list_tag, assert: 0x72
  uint8 :name_length
  string :name, read_length: :name_length
end

class Response < BinData::Record
  array :codes, type: :entry
end
```

As you can see, there's no leading byte to indicate how many codes are returned, so I can't set the `initial_length` of the array, and there are trailing bytes which are unrelated, so I can't use `:read_until => :eof`.

I'm thinking that a `nextbyte` variable should be exposed to the lambda passed to `read_until`, so that I can do something like `array :codes, type: :entry, read_until: lambda { nextbyte != 0x72 }`.

From a quick look I'd need to define `IO#peekbytes(n)` and add `:nextbyte => self.peekbytes(1)` to the `variables` Hash inside `ReadUntilPlugin#do_read(io)`.

Thoughts?

**Comment by dmendel** [comment]
I'm not familiar with the Yubikey format and didn't find any details from a cursory search.

From your sample string I'm guessing that "\x90" is a tag byte and not actual data.

If the yubikey is a typical type-length-value format then see https://github.com/dmendel/bindata/wiki/FAQ#how-do-i-model-this-complex-nested-format

A similar question was asked in #39, and so check out that issue and my response.

If the format isn't type-length-value, then point me to a spec and I'll try to help.

**Comment by jamesottaway** [comment]
Ah yeah, I should have included the protocol spec. The one I mentioned above is the List instruction: https://developers.yubico.com/ykneo-oath/Protocol.html

The response I'm trying to reading uses `0x72` as the byte to represent the start of each code, followed by the overall response status, which was `\x90\x00` to represent success in my example.

Most of the responses use type-length-value, but it doesn't seem to be used for repeated sections of a single response, like my example above.

**Comment by dmendel** [comment]
I think a buffer may be what you need:
https://github.com/dmendel/bindata/wiki/AdvancedTopics#buffers
```
class Response < BinData::Record
  count_bytes_remaining :response_length
  buffer :codes, length: -> { response_length - 2 } do
    array type: :entry,  read_until: :eof
  end
  uint16be :status
end
```

**Comment by jamesottaway** [comment]
Cool I'll go with that for now, thanks for your help!

I'm still curious what your thoughts are on my original idea? I was thinking that a solution based on peeking at the next tag byte might be a little more obvious.

**Comment by dmendel** [comment]
I am not in favour of your `nextbyte` suggestion for several reasons.

* It is undefined at end of file.
* In file formats, lists usually have either a prefix length or a terminator marker. An unusual list structure should be made obvious by an unusual declaration. Using `nextbyte` makes it easy for a reader to confuse this unusual case with the common case of a list with a terminator marker.

    ```ruby
    array type: :uint8, read_until: -> { element == 0 }
    ```
    ```ruby
    array type: :uint8, read_until: -> { nextbyte != 0 }
    ```
* I believe `nextbyte` encourages the programmer to think in an imperative rather than declarative manner.

But thank you for the suggestion.
