### ISSUE TITLE
Pre-filled fixed length arrays reading and writing

### ISSUE THREAD

**Issue by marnunez** [dmendel/bindata#61]
First of all, thank you for your wonderful work with the BinData gem, working declaratively with binary data in ruby feels incredibly natural. Just a glance at a class and it nearly documents itself!
I have a question though regarding consecutive fixed arrays.

I have a binary file with (among other fields) 4 pre-filled int16le arrays. Each array is of length 12 int16, and each value comes pre-filled with a -1 by default

    -1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1

Each time a value is added, a -1 is replaced. E.g.:

    15	16	21	-1	-1	-1	-1	-1	-1	-1	-1	-1

The 4 arrays are consecutive, and might be empty (all minus ones). 
My question is: is it possible to read until the first occurrence of a -1, while writing the file filling the array with -1 if empty? If so, my arrays are consecutive. How do I skip the "-1" that are left over in between arrays?

Thanks in advance

Marcos

**Comment by dmendel** [comment]
I may not completely understand your question so correct me if I misunderstand.

I think you are asking about how to present the arrays to ruby code by hiding the left over "-1".

So for your example above, calling `#inspect` on the object would result in something like
```ruby
my_arr[15, 16, 21]
```
rather than
```ruby
my_arr[15, 16, 21, -1, -1, -1, -1, -1, -1, -1, -1, -1]
```
Does this achieve what you want?
```ruby
require 'bindata'
require 'pp'

class CustomArray < BinData::Array
  default_parameter initial_length: 12
  default_parameter type: [:uint16le, initial_value: -1]

  def snapshot
    arr = []
    each do |el|
      break if el == -1
      arr << el
    end
    arr
  end

  def append(obj)
    each_with_index do |el, i|
      if el == -1
        self[i] = obj
        break
      end
    end
  end
end

c = CustomArray.new
c.append(3)
pp c
pp c.to_binary_s
```
