### ISSUE TITLE
get data by index

### ISSUE THREAD

**Issue by lanjingyu** [dmendel/bindata#65]
in c code
recv(socket, recvbuffer, 5, 0)
the received binary data maybe like this:
int *k=(int *)&debuffer[42];  
char *p=(char *)&debuffer[68];
k maybe timestamp or something else.
p may the some string.

**Comment by dmendel** [comment]
I recommend that you read the documentation in the wiki.  It should
answer this and your previous questions.

If you still have questions after reading the documentation, then do
ask.
