### ISSUE TITLE
Question: skipping junk

### ISSUE THREAD

**Issue by retorquere** [dmendel/bindata#68]
I'm reading a format where it is allowed to have whitespace before the start of a chunk of actual data. Is there a way to read over this? There is a clear character that marks start-of-chunk (a `|`).

**Comment by dmendel** [comment]
> I'm reading a format where it is allowed to have whitespace before the start of a chunk of actual data.

Are you sure this is a binary format?  If it's a text format then https://github.com/tenderlove/racc is probably what you want.

Is this a publically documented format?

**Comment by retorquere** [comment]
The format is documented at http://www.imc-benelux.nl/download-center/product-downloads/imc-shared-components/ ; as it requires a login I've also attached the file. The document is pretty big, but the relevant part is 5.13. The file is binary (the early part of 5.13 talks about the endianness of the numbers in the file, and the floating point format), although parts are easily parsed as text (ASCII even I think). Why they allow for padding -- no idea. Real data files can clearly not be crafted in Notepad. It can of course be read by a racc-generated parser, but the bulk of the format is (I think) well-suited to bindata.

[imcSharedComponents.pdf](https://github.com/dmendel/bindata/files/43982/imcSharedComponents.pdf)

**Comment by dmendel** [comment]
> http://www.imc-benelux.nl/download-center/product-downloads/imc-shared-components/

A recursive descent parser is the best solution to parse this format, imho.  The format is mainly text, with some numbers represented in binary.  BinData wouldn't be a good tool to write a parser in.

**Comment by retorquere** [comment]
Bummer, but good to know.
