### ISSUE TITLE
Perform operation on self within lambda

### ISSUE THREAD

**Issue by eikcam** [dmendel/bindata#70]
Is it possible to perform operations on values at the time of their creation? Below is a snippet that I have tried however it fails so is clearly incorrect.

`uint16be :grossWeight, :value => lambda { grossweight * 15 }`

I have tried using a temp value and then a virtual but that leads to its own issues as having mutiple temp variables fails with a duplication error.

```
uint16be :temp
virtual :grossWeight, :value => lambda { temp * 15 }
```

Any help would be greatly appreciated.

**Comment by dmendel** [comment]
The cleanest way would be to create a new primitive type that handles the multiplication for you automatically.

Something like this:

```ruby
class MyInt < BinData::Primitive
  default_parameter :factor => 1
  uint16be :the_int

  def get
    self.the_int * eval_parameter(:factor)
  end

  def set(val)
    self.the_int = val / eval_parameter(:factor)
  end
end
```

Use it like:

```ruby
my_int :gross_weight, :factor => 15
```

**Comment by eikcam** [comment]
Awesome! That works perfectly. Will allow me to tidy up a lot of temp values I hold and make everything nice and tidy.

Is there a forum to ask questions like this to avoid loading up the Issues page?

Thanks heaps.

**Comment by dmendel** [comment]
> Awesome! That works perfectly. Will allow me to tidy up a lot of temp
> values I hold and make everything nice and tidy.

You're welcome.

> Is there a forum to ask questions like this to avoid loading up the Issues page?

Email is fine.
