### ISSUE TITLE
[Question] choice does not appear to chose the right branch

### ISSUE THREAD

**Issue by ccoenen** [dmendel/bindata#71]
I have a piece of data that is pre-defined (i.e. i can't change the binary form). It looks like this:

```ruby
      class DataBlock < BinData::Record
        endian :little
        uint8 :type
        uint16 :payload_size
        buffer :data, length: :payload_size do
          choice :data, selection: :type do
            array 1, type: :subtype1, read_until: :eof
            array 2, type: :subtype2, read_until: :eof
            rest :default
          end
        end
      end
```

I do receive the number "1" as type, but still, all of my data is bunched up into a single string:

```ruby
{
  :type=>1,
  :payload_size=>12,
  :data=>"\x95\x02W\xF3\x9D\x00\e\xF3\x9B\x01\x1E\xF3"
}
```

If I remove the `rest :default` the application will crash and report 

> `IndexError: selection '#<BinData::SanitizedPrototype:0x007f963bea3ea8>' does not exist in :choices for obj.data_blocks[0].data`

**Comment by ccoenen** [comment]
And a sub-question would be: right now, i tell array to `read_until: :eof` will that actually be `eof` or is this limited to the surrounding buffer section?

**Comment by dmendel** [comment]
Thanks for the bug report. A quick workaround is to rename the field `type` to anything else. It seems there is a conflict with that name.

As to your sub question. `read_until: :eof` inside a buffer will be limited to the buffer section. It won't read until the end of the input stream.

**Comment by ccoenen** [comment]
Amazing! Thanks for responding so quickly. I will try it right now!

**Comment by dmendel** [comment]
Here is the equivalent code to show the problem:
```ruby
class MyChoice < BinData::Choice
  array 1, type: :subtype1, read_until: :eof
  array 2, type: :subtype2, read_until: :eof
  rest :default
end

class DataBlock < BinData::Record
  endian :little
  uint8 :type
  uint16 :payload_size
  buffer :data, type: [:my_choice, {selection: :type}], length: :payload_size
end
```
The `type` that selection is choosing is the `type` used by the buffer, not the `type` field in the DataBlock.

I'll make `type` a reserved word in the next release.

**Comment by ccoenen** [comment]
renaming instantly fixed my problem. I wish to thank you again for your kind support!

**Comment by dmendel** [comment]
You're very welcome.
