### ISSUE TITLE
[Question] Changing the field type whilst writing

### ISSUE THREAD

**Issue by xavriley** [dmendel/bindata#72]
Firstly thanks for writing such a great and useful library!

Reducing my problem down, I have a binary spec with multiple "versions" where version 1 used `int16` for some fields and version 2 bumped those up to `int32`. The version number is specified in a field and I've managed to parse these by making use of the `choice` parameter:

```
class Synthdef < BinData::Record
  def check_version
    # Spec calls for 1 based indexing (so version 1 or version 2)
    # Returns zero based index for choices
    eval_parameter(:file_version) == 1 ? 0 : 1
  end

  int32 :file_version
  
  choice        :no_of_constants, :selection => lambda { check_version }, :choices => {0 => :int16, 1 => :int32}
end
```

What I'd like to be able to do is *convert* a record from one version (with `:int16`) to another (with `:int32`). I thought I might be able to do this by `assign`ing a version number and then writing it out with `#write` but I can see that it doesn't change the choice field automatically. Is there a way to achieve this otherwise?

For a little more context, this is part of a project to parse SuperCollider synth definitions which are little graphs that describe how to link synthesizer components together https://github.com/xavriley/synthdef The complete spec for the binary format is available at http://doc.sccode.org/Reference/Synth-Definition-File-Format.html

Thanks again.

**Comment by dmendel** [comment]
> What I'd like to be able to do is *convert* a record from one version (with `:int16`) to another (with `:int32`).

https://github.com/dmendel/bindata/wiki/CompoundTypes#copy_on_change

`:copy_on_change` will do this for you.

**Comment by xavriley** [comment]
Perfect! Thanks so much. I managed to implement this over at https://github.com/xavriley/synthdef

**Comment by dmendel** [comment]
You can refactor this to:

```ruby
class SynthInt < BinData::Choice
  endian :big
  default_parameter :selection => :check_version
  default_parameter :copy_on_change => true

  int16 0
  int32 1
end
```
and then you can use
```ruby
synth_int :no_of_constants
```
instead of
```ruby
choice :no_of_constants, :selection => :check_version, :copy_on_change => true, :choices => {0 => :int16, 1 => :int32}
```
