### ISSUE TITLE
Create instance variable in BinData::Record subclass that isn't read

### ISSUE THREAD

**Issue by peterjmorgan** [dmendel/bindata#76]
I'm trying to figure out how to instantiate an instance variable within a record to expose as a variable, but not have it read during input parsing.

For example:
```
class Testy < BinData::Record
    uint32be :test
    uint32be :test2, :length => 0, :value => lambda {test}, :read_length => 0
end

if $0 == __FILE__
  test = Testy.new()
  val = "\x01\x39\x99\xff"
  test.read(val)
  puts test.test2.to_binary_s

  binding.pry
end
```
I've tried changing the read_length and length params, and connecting it to test via lambdas, and using method_missing but I haven't found out a good way for doing this.

Any help is greatly appreciated!

**Comment by dmendel** [comment]
You can use either `:onlyif` or virtual fields.

For your example you can use

```
class Testy < BinData::Record
  uint32be :test
  uint32be :test2, :value => :test, :onlyif => false
end
```

**Comment by peterjmorgan** [comment]
Hmm, that doesn't appear to allow me to invoke
```
t = Testy.new
t.read(input)
t.test2
```
And have test2 equal to test

I'll keep trying some other things, but your quick help is hugely appreciated!

**Comment by dmendel** [comment]
What do you mean by "expose as a variable"? What methods do you wish to invoke on this field?

You could specify a virtual field as follows. If this doesn't meet your needs then you'll need to be more specific in what you want to achieve.

```ruby
class Testy < BinData::Record
  uint32be :test
  virtual :test2, :value => :test
end
```
