### ISSUE TITLE
Name resolution behavior seems inconsistent with endian and search_prefix

### ISSUE THREAD

**Issue by michaeljpetter** [dmendel/bindata#80]
Using both *endian* and *search_prefix* together doesn't resolve the way I'd expect.

If a child record is not endian-specific, here's what happens:

```ruby
class NSChild < BinData::Record; end

class NSParent1 < BinData::Record
  ns_child  # works
end

class NSParent2 < BinData::Record
  endian :little
  ns_child  # works
end

class NSParent3 < BinData::Record
  search_prefix :ns
  child   # works
end

class NSParent4 < BinData::Record
  endian :little
  search_prefix :ns
  child   # unknown type 'child' in NSParent4 (TypeError)
end
```

Since *NSParent2*, an endian-specific record, resolves the endian-agnostic *NSChild*, why does adding a *search_prefix* (*NSParent4*) cause resolution to fail, when the *search_prefix* alone doesn't (*NSParent3*)?

**Comment by dmendel** [comment]
This is a bug. Thanks for the report.
