### ISSUE TITLE
Q: hetereogenous array of Choice?

### ISSUE THREAD

**Issue by jrochkind** [dmendel/bindata#81]
Is there any way to have a hetereogenous array of choice?

In the situation I'm in (OpenType/TrueType), there's an initial directory which specifies the offsets and lengths of 1 to N 'tables', each of which has a different internal structure. 

Any advice for how to tackle that? 

I'm trying to take advantage of the awesomeness of bindata to make a data structure that is editable and writeable too, and I'm having trouble figuring out how to approach this aspect.

**Comment by dmendel** [comment]
> Is there any way to have a hetereogenous array of choice?

There is a existing example at:
  https://github.com/dmendel/bindata/blob/master/examples/nbt.rb

Specifically, look at the TagList class.

> I'm trying to [...] make a data structure that is editable and writeable too, and I'm having trouble figuring out how to approach this aspect. 

1. Start with an implementation that only supports reading.

2. Identify all fields referenced in `:read_until`, `:read_length`, `:initial_length` lambdas.

3. Ensure these referenced fields have a `:value` argument that is correct for writing.

**Comment by jrochkind** [comment]
Thanks @dmendel that's helpful advice. (And btw, bindata is an incredibly well-designed and implemented tool, very impressive, thanks!)

I have been spending some time with the nbt example, and it's useful to see some possibilities, although in my case I don't actually need a recursive definition at all. 

I think I am on a succesful path now, although my code definitely isn't very efficient, it's re-calculating certain things in multiple different lambda params. 

But it looks like you _can_ just have an array of choices. Is there any reason this is a bad idea? It seems to work:

    array :tables, initial_length: :num_tables do
      choice(selection: lambda {
             # simplification of real data but we do need a lookup here
             directory_entries.find { |entry| entry.tableIndex == index }.table_type
      }) do
         # some table types have specific record classes we've made
         meta_table 'meta'

         # for others, we just put it in an opaque binary string
         string :default, read_length: lambda {
             # sadly need to repeat the lookup to get proper length
             directory_entries.find { |entry| entry.tableIndex == index }.tableLength
         }
     end

This _seems_ to be working, I think. Any reason an array of choices, or any other parts of this implementation, seem like a mistake or something that has a better way to do it?

Thanks very much for your advice and for the bindata tool!

**Comment by dmendel** [comment]
Your array of choices looks good to me.

BinData prioritises readability over speed.  If speed becomes an issue
for you then let me know and I'll be able to make some suggestions.
