### ISSUE TITLE
Can't read array

### ISSUE THREAD

**Issue by Ogromny** [dmendel/bindata#82]
Hi,
I try everything, but i can't read an array from a file :/
Here the code:
```ruby
require 'bindata'

class Pavels < BinData::Record
    array :pavel do
        string :lieu
        string :info
    end
end

io = File.open('test', 'w')
pavels = Pavels.new
pavels.pavel << {:appl => 'tox', :lieu => 'ogromny', :info => 'admin'}
pavels.write(io)

io = File.open('test', 'r')
pavels = Pavels.new
pavels.read(io)
puts pavels
```

Thanks in advance :)
I'm French so sorry if my english was bad :/

**Comment by dmendel** [comment]
You need to give the array length.

https://github.com/dmendel/bindata/wiki/CompoundTypes#array-parameters

Use either `:initial_length` or `:read_until`.

You probably want something like:

```ruby
class Pavels < BinData::Record
  array :pavel, :read_until => :eof do
    string :lieu
    string :info
  end
end
```

**Comment by Ogromny** [comment]
Thanks, but now when i do 
```ruby
io = File.open('test', 'r')
pavels = Pavels.new
pavels.read(io)
puts pavels
```

It's make a loop, What i'm doing wrong ?

**Comment by dmendel** [comment]
https://github.com/dmendel/bindata/wiki/PrimitiveTypes#strings

You need to also specify the length of the strings as well.

**Comment by Ogromny** [comment]
Thanks, but where i need to add :length ?

I'm very poor sorry :/

**Comment by dmendel** [comment]
BinData may not suit your needs. Maybe [JSON](http://ruby-doc.org/stdlib-2.0.0/libdoc/json/rdoc/JSON.html) or [Marshal](http://ruby-doc.org/core-2.3.0/Marshal.html) is better for you.

For your example, use either
```ruby
class Pavels < BinData::Record
  array :pavel, :read_until => :eof do
    stringz :lieu
    stringz :info
  end
end
```
or
```ruby
class Pavels < BinData::Record
  array :pavel, :read_until => :eof do
    uint32le :lieu_length, :value => lambda { lieu.num_bytes }
    string :lieu, :read_length => :lieu_length

    uint32le :info_length, :value => lambda { info.num_bytes }
    string :info, :read_length => :info_length
  end
end
```

**Comment by Ogromny** [comment]
Yes certainly thanks ;)
