### ISSUE TITLE
How to raise a custom error when assert fails?

### ISSUE THREAD

**Issue by sebroeder** [dmendel/bindata#85]
I am just getting started with `bindata` and have the following simple class:

```ruby
class FileHeader < BinData::Record
  VALID_HEADER_SIZES = [12, 14].freeze

  endian :little
  uint8  :header_size, assert: -> { VALID_HEADER_SIZES.include?(value) }
end
```

The class works as expected but I’d like to raise a custom error under the namespace of my own gem instead of BinData::ValidityError when the assertion on header_size fails. Is this possible?

Thank you for working on `bindata`, so far the gem is really pleasant to use.

**Comment by dmendel** [comment]
You can't change the exception, but you can rescue and re-raise a
different exception in your own code.

There is an example of doing that here:
    https://github.com/dmendel/bindata/blob/master/lib/bindata/dsl.rb#L196

**Comment by sebroeder** [comment]
Thanks. The only downside of your recommendation is that I can only rescue and re-raise in the calling code, not the BinData::Record subclass itself, but I think I can make that work.
