### ISSUE TITLE
How to get the position of an object in a file

### ISSUE THREAD

**Issue by karl-petter** [dmendel/bindata#87]
I'm using https://github.com/tjwallace/fit to parse FIT-files. It is based on BinData. Though some files from some customers fail and now I'm trying to debug why and correct the parsing. A FIT file is basically file header followed by an array of records where each record has a header followed by a number of definition records and data records. One of these record headers fails the parsing and now I would like to find out why and thus investigate where in the file the failing header is situated. Thus I thought I could use #abs_offset to get the position of the record header object in the file but it returns 0 which is not correct since that is where the file header is.

The rubydoc documentation for #abs_offset says: "Returns the offset (in bytes) of this object with respect to its most distant ancestor." And in the Wiki documentation "Returns the offset of this object with respect to the most distant ancestor structure it is contained within. This is most likely to be used with arrays and records. Compare this to #rel_offset." and an example with BinDataArray is given. So what does this means? Does #abs_offset only works for nested records like in the array example? Any suggestion on how to find out where in a large binary file an object has been or is being parsed from so one can give a positional reference in an exception for instance?

**Comment by dmendel** [comment]
`#abs_offset` is not what you want. You want `IO#pos` instead.

At or around https://github.com/tjwallace/fit/blob/master/lib/fit/file/record.rb#L19, do something like
```
puts io.pos
BinData::trace_reading
@header = RecordHeader.read(io)
```

**Comment by karl-petter** [comment]
That works fine for the problem I have. Thanks!

But in general would it not be nice to have a reference in each data object that references where in a file the object comes from? For instance to use when reporting an error in a file structure that cannot be parsed using the given model.

**Comment by dmendel** [comment]
No, for two reasons.
1. Not all streams are seekable - think pipes or network sockets.
2. Adding unnecessary objects to each BinData object would significantly increase the memory requirements.
