### ISSUE TITLE
How to expose mandatory_parameter in #snapshot?

### ISSUE THREAD

**Issue by sbulka** [dmendel/bindata#89]
To parse a binary format, i use classes similar to those at the end of this issue.
I have two questions on code style:

1. is there an easier way to expose the manadatory_parameter to #snapshot than the virtual field?
2. the Payload class has many more lines/records following.
Some Records depend on options, the others wont be harmed if they get options passed.
Is there a DRY way to do this?
It would be ok to always pass options to the record.
Unneccessary options will be ignored by records.

I was struggling with this because i have to read the options before knowing which record to choose.
Took some time to figure out this solution, but I'm not yet happy with it :/

```ruby
require 'bindata'

class RecordZero < BinData::Record
  mandatory_parameter :_options
  bit4 :lowbit, :onlyif => lambda { _options & 0x1 > 0 }
  bit4 :highbit, :onlyif => lambda { _options & 0x1 > 0 }
  virtual :options, :value => :_options
end

class RecordOne < BinData::Record
  int8 :byte
end

class Payload < BinData::Choice
  opt = {:_options => :tag_options}
  record_zero 0, opt
  record_one 1
    ...
    ...
end

class RecordRead < BinData::Record
  bit4 :tag_options
  bit4 :tag
  payload :payload, :selection => :tag, :tag_options => :tag_options
end
```

**Comment by dmendel** [comment]
1. Using a virtual field as you do is the easiest way to expose parameters. This is a deliberate design decision, to encourage users to restructure their solution (see below).

2. Passing extra options is fine, they will be ignored by objects that don't use them.

As you can see from your supplied code, this approach quickly turns ugly.

I would write your example as:
```ruby
require 'bindata'

class RecordZero < BinData::Record
  # unchanged
end

class RecordZero_0x0 < RecordZero
  default_parameter _options: 0x0
end

class RecordZero_0x1 < RecordZero
  default_parameter _options: 0x1
end

...

class Payload < BinData::Choice
  record_zero_0x0 (0 << 4) + 0
  record_zero_0x1 (1 << 4) + 0
  ...
  record_one_0x0 (0 << 4) + 1
  record_one_0x1 (1 << 4) + 1
  ...
end

class RecordRead < BinData::Record
  bit4 :tag_options
  bit4 :tag
  payload :payload, :selection => lambda { (tag_options << 4) + tag }
end
```
which then leads to the obvious refactoring

```ruby
class Payload < BinData::Choice
  # note the re-ordering
  record_zero_0x0  0
  record_one_0x0   1
  record_tow_0x0   2
  ...
  record_zero_0x1 16
  record_one_0x1  17
  ...
end

class RecordRead < BinData::Record
  uint8 :tagged_options
  payload :payload, :selection => :tagged_options
end
```

The `Payload` class can probably be autogenerated and the whole declaration become more straightforward to read.

**Comment by sbulka** [comment]
The approach of autogenerating theses wrapper classes sounds interesting.
Never did that before, but its a good way to learn some more new things.
Doesn't sound too hard.

Thank you for your reply, and keep up the good work! :)
