### ISSUE TITLE
Trim padding when writing

### ISSUE THREAD

**Issue by arif-trackmy** [dmendel/bindata#91]
Defined a record with length defined for each field:
```
class Transmission < BinData::Record
  string :begin_trans, length: 10, initial_value: 'TA12345678'
  string :code, length: 5, trim_padding: true
  string :end_trans, length: 10, initial_value: 'TB12345678'
end

transmission = Transmission.new({code: 'LS01'})
transmission.to_binary_s
```

The max length of code field should be 5 but it can be of length 4. The issue is it adds pad_bytes at the end of the string and the server throws a validation failed exception. 

I want to trim padding when writing so that it adjusts with data provided.

**Comment by dmendel** [comment]
Your requirements are unclear. Could you provide some examples of what you require, including edge cases?

Does `:read_length` work better for you than `:length`?

**Comment by arif-trackmy** [comment]
Actually I want to trim the pad_bytes if the value of a field is less than the specified length. In the code above the length of code field is 5 but if a user provide value of length 4 'LS01' it should not append the pad_bytes.

**Comment by dmendel** [comment]
Your requirements are still unclear. From what I can gather, you want either:
```
class Transmission < BinData::Record
  string :begin_trans, length: 10, initial_value: 'TA12345678'
  string :code, read_length: 5
  string :end_trans, length: 10, initial_value: 'TB12345678'
end
```
or
```
class StrippedString < BinData::Primitive
  mandatory_parameter :max_length

  string :stripped, read_length: :max_length

  def set(val)
    self.stripped = val.sub(/\0*\z/, "")
  end

  def get
    self.stripped
  end
end

class Transmission < BinData::Record
  string :begin_trans, length: 10, initial_value: 'TA12345678'
  stripped_string :code, max_length: 5
  string :end_trans, length: 10, initial_value: 'TB12345678'
end
```

**Comment by arif-trackmy** [comment]
The `StrippedString` implementation works fine. Thanks for the help.
