### ISSUE TITLE
Byte-Alignment for arrays (howto-question)

### ISSUE THREAD

**Issue by ccoenen** [dmendel/bindata#94]
(this is related to https://github.com/dmendel/bindata/issues/93#issuecomment-325870022 - but I didn't want to hijack the issue for my Q&A)

I have two classes, one is an item in a list. The other is a container for those list items. The *item* needs to be `byte_align: 4`. Here's a paraphrased version of my code:

```ruby
  class Item < BinData::Record
    uint16 :block_type            # , byte_align: 4 <--- POSSIBILITY 3
    uint16 :payload_size
    buffer :data, length: :payload_size do      # , byte_align: 4 (before the _do_) <--- POSSIBILITY 2
      choice :data, selection: :block_type do
        # can be pretty much any number of bytes
      end
    end
     # skip length: -> { ((4 - (payload_size % 4)) % 4) } # POSSIBILITY 4
  end

  class Container < BinData::Record
    uint32 :timestamp
    uint16 :timestamp_ms
    skip length: 2

    array :items, type: :item, read_until: :eof # , byte_align: 4 <--- POSSIBILITY 1
  end
```

The code snippet has four places, where I tried the byte_align for the item-array. Each item's start should be on a 4-byte-boundary.

* Possibility 1 (the container's `array` statement) does not work, I guess the field itself will be aligned, but not its contents.
* Possibility 2 (the item's `buffer` statement) does not work, perhaps it only sees its own byte counter (if there is such a thing?)
* Possibility 3 (the item's first field) does not work, perhaps for the same reason.
* Possibility 4 (the item's `skip` with lambda-length) is my workaround for now. It appears to work as intended.

Did I miss anything? Do you see a better way? I do have a working version, and the skip-plus-lambda-length approach is easy enough to read. If I could use the byte_align, it would be even more expressive.

**Comment by dmendel** [comment]
`byte_align` aligns the field to the top of the enclosing record rather than the current stream position (i.e. `#rel_offset` not `#abs_offset`. This is why possibilities 2 and 3 don't work as expected.

I'd probably change possibility 4 to make it a bit more expressive.
```ruby
skip length: 0, byte_align: 4
```
A possible gotcha with possibility 4 is that padding will be read after the end of the array.

**Comment by ccoenen** [comment]
skip with byte_align looks nice! certainly better than my solution. Thanks!
