### ISSUE TITLE
bit1 query method always returns true

### ISSUE THREAD

**Issue by paddor** [dmendel/bindata#96]
The documentation says that `bit1` fields can be used as Booleans. To me, that means that given `bit1 :flag`, the method `#flag?` will return `true` or `false`, depending on whether it read a set or an unset bit. Unfortunately it seems to return `true` in both cases.

Here's a demo:

```ruby
require 'bindata'


class Foo < BinData::Record
  bit1 :bar
end
BinData.trace_reading do
  puts "testing for SET bit:"
  fail 'Foo#bar? should return true'  unless Foo.read("\x80").bar? == true
  puts "GOOD (Foo#bar? returned true)"
  puts

  puts "testing for UNSET bit:"
  fail 'Foo#bar? should return false' unless Foo.read("\x00").bar? == false
  puts "GOOD (Foo#bar? returned false)"
end
```

BinData 2.4.1 on Ruby 2.5.0 prints:
```
testing for SET bit:
obj.bar => 1
GOOD (Foo#bar? returned true)

testing for UNSET bit:
obj.bar => 0
Traceback (most recent call last):
	2: from bindata_bug.rb:10:in `<main>'
	1: from /home/p/.gem/ruby/2.5.0/gems/bindata-2.4.1/lib/bindata/trace.rb:32:in `trace_reading'
bindata_bug.rb:17:in `block in <main>': Foo#bar? should return false (RuntimeError)
```

Or am I doing something wrong?

**Comment by dmendel** [comment]
```ruby
class Foo < BinData::Record
  bit1 :bar
end
```
By boolean, it means
```ruby
foo.bar = true
```
is a shortcut for
```ruby
foo.bar = 1
```

Extracting the value:
```ruby
foo.bar == 1
```
and not
```ruby
foo.bar == true # wrong
```

> To me, that means that given bit1 :flag, the method #flag? will return true or false

No, the `?` suffix means test for an optional field. (See https://github.com/dmendel/bindata/wiki/Records#optional-fields)

The documentation for using `Bit1` as boolean could be clearer, so I'll fix that now.

Thanks for the report.

**Comment by paddor** [comment]
Oh, I see. Thanks for the clarification.
